---
services:
  grav:
    build: .
    container_name: grav
    restart: unless-stopped
    environment:
      - GRAV_MULTISITE=subdirectory
      - ROBOTS_DISALLOW=false
      - GRAV_PLUGINS=devtools,precache
    volumes:
      - ./grav/backup:/var/www/grav/backup
      - ./grav/logs:/var/www/grav/logs
      - ./grav/user:/var/www/grav/user
    ports:
      - 8001:80
