title: timmyb
default_lang: en
author:
  name: 'Tim Bryant'
  email: timothybryant3@gmail.com
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'my personal blog and website'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: ''
